[package]
name = "marked-wasm"
version = "0.1.0"
authors = ["yuta4j1 <kascado.ys10@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pulldown-cmark = { version = "0.5", default-features = false }
wasm-bindgen = "0.2"
